### 풀이 영상: https://youtu.be/QpNufh_ZV7A?t=181

# Q. 결측치가 제일 큰 값의 컬럼명을 구하시오
- data: t1-data1.csv

In [1]:
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification/t1-data1.csv")
df.head()

     id   age city    f1  f2    f4         f5
0  id01   2.0   서울   NaN   0  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  INFP  52.667078
4  id05  24.0   서울  85.0   2  ISFJ  29.269869

# Your Code

In [2]:
df = pd.DataFrame(df.isnull().sum(), columns=['cnt_null'])
df

      cnt_null
id           0
age          0
city         0
f1          29
f2           0
f4           0
f5           0

In [3]:
df = df['cnt_null'].sort_values(ascending=False)
df

f1      29
id       0
age      0
city     0
f2       0
f4       0
f5       0
Name: cnt_null, dtype: int64

In [4]:
print(df.index[0])

f1

# solution

In [5]:
import pandas as pd
df = pd.read_csv("../input/big-data-analytics-certification/t1-data1.csv")

df = pd.DataFrame(df.isnull().sum(), columns=['cnt_null'])
df = df['cnt_null'].sort_values(ascending=False)
print(df.index[0])

f1

In [6]:
# 풀이2
df = pd.read_csv("../input/big-data-analytics-certification/t1-data1.csv")
df = df.isnull().sum()
print(df.index[3])

f1