# T1-30. 12월 25일 결제 금액(price)은 12월 총 결제금액의 몇 %인가? (정수로 출력)

In [1]:
import pandas as pd
df = pd.read_csv("/kaggle/input/bigdatacertificationkr/payment.csv")
df

        date  hour    menu  price
0   20221129    13    딸기라떼   4000
1   20221130    12    카페라떼   3000
2   20221201    14   바닐라라떼   3500
3   20221201    16    초코라떼   3500
4   20221202    17    모카라떼   3500
5   20221202    12   카라멜라떼   3500
6   20221203     8   챠이 라떼   3500
7   20221203     9   아메리카노   2000
8   20221203    15   오곡 라떼   4000
9   20221203    16   아메리카노   2000
10  20221225    10   아메리카노   2000
11  20221225    14  토피넛 라떼   4000
12  20221225    16   카페 라떼   3000

In [2]:
# your code
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')
df['date']

0    2022-11-29
1    2022-11-30
2    2022-12-01
3    2022-12-01
4    2022-12-02
5    2022-12-02
6    2022-12-03
7    2022-12-03
8    2022-12-03
9    2022-12-03
10   2022-12-25
11   2022-12-25
12   2022-12-25
Name: date, dtype: datetime64[ns]

In [3]:
cond1 = df['date'].dt.month == 12
cond1

0     False
1     False
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
Name: date, dtype: bool

In [4]:
cond2 = df['date'].dt.day == 25
cond2

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
Name: date, dtype: bool

In [5]:
result = sum(df[cond1 & cond2]['price']) / sum(df[cond1]['price'])
result

0.2608695652173913

In [6]:
print(int(result*100))

26